[package]
name = "marcesquerra/idristest"
version = "0.1.3"
authors = []
description = "A testing framework for idris"
homepage = "https://github.com/marcesquerra/IdrisTest"
repository = "https://github.com/marcesquerra/IdrisTest"
keywords = ["test", "testing"]

[dependencies]

[targets.lib]
path = "src"
mods = [
    "Idristest"
]

